package cn.itcast.domain.cargo;

import cn.itcast.domain.BaseEntity;

import java.io.Serializable;
import java.util.Date;

public class Shipping extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.shipping_order_id
     *
     * @mbg.generated
     */
    private String shippingOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.shipping_type
     *
     * @mbg.generated
     */
    private String shippingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.shipper
     *
     * @mbg.generated
     */
    private String shipper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.bl_title
     *
     * @mbg.generated
     */
    private String blTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.original_notified_by
     *
     * @mbg.generated
     */
    private String originalNotifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.credit_letter
     *
     * @mbg.generated
     */
    private String creditLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.loading_port
     *
     * @mbg.generated
     */
    private String loadingPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.transhipment_port
     *
     * @mbg.generated
     */
    private String transhipmentPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.discharge_port
     *
     * @mbg.generated
     */
    private String dischargePort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.loading_time
     *
     * @mbg.generated
     */
    private Date loadingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.effective_time
     *
     * @mbg.generated
     */
    private Date effectiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.if_batches
     *
     * @mbg.generated
     */
    private String ifBatches;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.if_transshipment
     *
     * @mbg.generated
     */
    private String ifTransshipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.copies_no
     *
     * @mbg.generated
     */
    private String copiesNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.brief_description
     *
     * @mbg.generated
     */
    private String briefDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.requirements
     *
     * @mbg.generated
     */
    private String requirements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.freight_description
     *
     * @mbg.generated
     */
    private String freightDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.reviewer
     *
     * @mbg.generated
     */
    private String reviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.create_dept
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_shipping.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.shipping_order_id
     *
     * @return the value of co_shipping.shipping_order_id
     *
     * @mbg.generated
     */
    public String getShippingOrderId() {
        return shippingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.shipping_order_id
     *
     * @param shippingOrderId the value for co_shipping.shipping_order_id
     *
     * @mbg.generated
     */
    public void setShippingOrderId(String shippingOrderId) {
        this.shippingOrderId = shippingOrderId == null ? null : shippingOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.shipping_type
     *
     * @return the value of co_shipping.shipping_type
     *
     * @mbg.generated
     */
    public String getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.shipping_type
     *
     * @param shippingType the value for co_shipping.shipping_type
     *
     * @mbg.generated
     */
    public void setShippingType(String shippingType) {
        this.shippingType = shippingType == null ? null : shippingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.shipper
     *
     * @return the value of co_shipping.shipper
     *
     * @mbg.generated
     */
    public String getShipper() {
        return shipper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.shipper
     *
     * @param shipper the value for co_shipping.shipper
     *
     * @mbg.generated
     */
    public void setShipper(String shipper) {
        this.shipper = shipper == null ? null : shipper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.bl_title
     *
     * @return the value of co_shipping.bl_title
     *
     * @mbg.generated
     */
    public String getBlTitle() {
        return blTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.bl_title
     *
     * @param blTitle the value for co_shipping.bl_title
     *
     * @mbg.generated
     */
    public void setBlTitle(String blTitle) {
        this.blTitle = blTitle == null ? null : blTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.original_notified_by
     *
     * @return the value of co_shipping.original_notified_by
     *
     * @mbg.generated
     */
    public String getOriginalNotifiedBy() {
        return originalNotifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.original_notified_by
     *
     * @param originalNotifiedBy the value for co_shipping.original_notified_by
     *
     * @mbg.generated
     */
    public void setOriginalNotifiedBy(String originalNotifiedBy) {
        this.originalNotifiedBy = originalNotifiedBy == null ? null : originalNotifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.credit_letter
     *
     * @return the value of co_shipping.credit_letter
     *
     * @mbg.generated
     */
    public String getCreditLetter() {
        return creditLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.credit_letter
     *
     * @param creditLetter the value for co_shipping.credit_letter
     *
     * @mbg.generated
     */
    public void setCreditLetter(String creditLetter) {
        this.creditLetter = creditLetter == null ? null : creditLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.loading_port
     *
     * @return the value of co_shipping.loading_port
     *
     * @mbg.generated
     */
    public String getLoadingPort() {
        return loadingPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.loading_port
     *
     * @param loadingPort the value for co_shipping.loading_port
     *
     * @mbg.generated
     */
    public void setLoadingPort(String loadingPort) {
        this.loadingPort = loadingPort == null ? null : loadingPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.transhipment_port
     *
     * @return the value of co_shipping.transhipment_port
     *
     * @mbg.generated
     */
    public String getTranshipmentPort() {
        return transhipmentPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.transhipment_port
     *
     * @param transhipmentPort the value for co_shipping.transhipment_port
     *
     * @mbg.generated
     */
    public void setTranshipmentPort(String transhipmentPort) {
        this.transhipmentPort = transhipmentPort == null ? null : transhipmentPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.discharge_port
     *
     * @return the value of co_shipping.discharge_port
     *
     * @mbg.generated
     */
    public String getDischargePort() {
        return dischargePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.discharge_port
     *
     * @param dischargePort the value for co_shipping.discharge_port
     *
     * @mbg.generated
     */
    public void setDischargePort(String dischargePort) {
        this.dischargePort = dischargePort == null ? null : dischargePort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.loading_time
     *
     * @return the value of co_shipping.loading_time
     *
     * @mbg.generated
     */
    public Date getLoadingTime() {
        return loadingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.loading_time
     *
     * @param loadingTime the value for co_shipping.loading_time
     *
     * @mbg.generated
     */
    public void setLoadingTime(Date loadingTime) {
        this.loadingTime = loadingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.effective_time
     *
     * @return the value of co_shipping.effective_time
     *
     * @mbg.generated
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.effective_time
     *
     * @param effectiveTime the value for co_shipping.effective_time
     *
     * @mbg.generated
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.if_batches
     *
     * @return the value of co_shipping.if_batches
     *
     * @mbg.generated
     */
    public String getIfBatches() {
        return ifBatches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.if_batches
     *
     * @param ifBatches the value for co_shipping.if_batches
     *
     * @mbg.generated
     */
    public void setIfBatches(String ifBatches) {
        this.ifBatches = ifBatches == null ? null : ifBatches.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.if_transshipment
     *
     * @return the value of co_shipping.if_transshipment
     *
     * @mbg.generated
     */
    public String getIfTransshipment() {
        return ifTransshipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.if_transshipment
     *
     * @param ifTransshipment the value for co_shipping.if_transshipment
     *
     * @mbg.generated
     */
    public void setIfTransshipment(String ifTransshipment) {
        this.ifTransshipment = ifTransshipment == null ? null : ifTransshipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.copies_no
     *
     * @return the value of co_shipping.copies_no
     *
     * @mbg.generated
     */
    public String getCopiesNo() {
        return copiesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.copies_no
     *
     * @param copiesNo the value for co_shipping.copies_no
     *
     * @mbg.generated
     */
    public void setCopiesNo(String copiesNo) {
        this.copiesNo = copiesNo == null ? null : copiesNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.brief_description
     *
     * @return the value of co_shipping.brief_description
     *
     * @mbg.generated
     */
    public String getBriefDescription() {
        return briefDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.brief_description
     *
     * @param briefDescription the value for co_shipping.brief_description
     *
     * @mbg.generated
     */
    public void setBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription == null ? null : briefDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.requirements
     *
     * @return the value of co_shipping.requirements
     *
     * @mbg.generated
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.requirements
     *
     * @param requirements the value for co_shipping.requirements
     *
     * @mbg.generated
     */
    public void setRequirements(String requirements) {
        this.requirements = requirements == null ? null : requirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.freight_description
     *
     * @return the value of co_shipping.freight_description
     *
     * @mbg.generated
     */
    public String getFreightDescription() {
        return freightDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.freight_description
     *
     * @param freightDescription the value for co_shipping.freight_description
     *
     * @mbg.generated
     */
    public void setFreightDescription(String freightDescription) {
        this.freightDescription = freightDescription == null ? null : freightDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.reviewer
     *
     * @return the value of co_shipping.reviewer
     *
     * @mbg.generated
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.reviewer
     *
     * @param reviewer the value for co_shipping.reviewer
     *
     * @mbg.generated
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.state
     *
     * @return the value of co_shipping.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.state
     *
     * @param state the value for co_shipping.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.create_by
     *
     * @return the value of co_shipping.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.create_by
     *
     * @param createBy the value for co_shipping.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.create_dept
     *
     * @return the value of co_shipping.create_dept
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.create_dept
     *
     * @param createDept the value for co_shipping.create_dept
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.create_time
     *
     * @return the value of co_shipping.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.create_time
     *
     * @param createTime the value for co_shipping.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.company_id
     *
     * @return the value of co_shipping.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.company_id
     *
     * @param companyId the value for co_shipping.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_shipping.company_name
     *
     * @return the value of co_shipping.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_shipping.company_name
     *
     * @param companyName the value for co_shipping.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}