package cn.itcast.domain.cargo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShippingExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public ShippingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShippingOrderIdIsNull() {
            addCriterion("shipping_order_id is null");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdIsNotNull() {
            addCriterion("shipping_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdEqualTo(String value) {
            addCriterion("shipping_order_id =", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdNotEqualTo(String value) {
            addCriterion("shipping_order_id <>", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdGreaterThan(String value) {
            addCriterion("shipping_order_id >", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("shipping_order_id >=", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdLessThan(String value) {
            addCriterion("shipping_order_id <", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdLessThanOrEqualTo(String value) {
            addCriterion("shipping_order_id <=", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdLike(String value) {
            addCriterion("shipping_order_id like", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdNotLike(String value) {
            addCriterion("shipping_order_id not like", value, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdIn(List<String> values) {
            addCriterion("shipping_order_id in", values, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdNotIn(List<String> values) {
            addCriterion("shipping_order_id not in", values, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdBetween(String value1, String value2) {
            addCriterion("shipping_order_id between", value1, value2, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingOrderIdNotBetween(String value1, String value2) {
            addCriterion("shipping_order_id not between", value1, value2, "shippingOrderId");
            return (Criteria) this;
        }

        public Criteria andShippingTypeIsNull() {
            addCriterion("shipping_type is null");
            return (Criteria) this;
        }

        public Criteria andShippingTypeIsNotNull() {
            addCriterion("shipping_type is not null");
            return (Criteria) this;
        }

        public Criteria andShippingTypeEqualTo(String value) {
            addCriterion("shipping_type =", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeNotEqualTo(String value) {
            addCriterion("shipping_type <>", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeGreaterThan(String value) {
            addCriterion("shipping_type >", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("shipping_type >=", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeLessThan(String value) {
            addCriterion("shipping_type <", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeLessThanOrEqualTo(String value) {
            addCriterion("shipping_type <=", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeLike(String value) {
            addCriterion("shipping_type like", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeNotLike(String value) {
            addCriterion("shipping_type not like", value, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeIn(List<String> values) {
            addCriterion("shipping_type in", values, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeNotIn(List<String> values) {
            addCriterion("shipping_type not in", values, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeBetween(String value1, String value2) {
            addCriterion("shipping_type between", value1, value2, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShippingTypeNotBetween(String value1, String value2) {
            addCriterion("shipping_type not between", value1, value2, "shippingType");
            return (Criteria) this;
        }

        public Criteria andShipperIsNull() {
            addCriterion("shipper is null");
            return (Criteria) this;
        }

        public Criteria andShipperIsNotNull() {
            addCriterion("shipper is not null");
            return (Criteria) this;
        }

        public Criteria andShipperEqualTo(String value) {
            addCriterion("shipper =", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperNotEqualTo(String value) {
            addCriterion("shipper <>", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperGreaterThan(String value) {
            addCriterion("shipper >", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperGreaterThanOrEqualTo(String value) {
            addCriterion("shipper >=", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperLessThan(String value) {
            addCriterion("shipper <", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperLessThanOrEqualTo(String value) {
            addCriterion("shipper <=", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperLike(String value) {
            addCriterion("shipper like", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperNotLike(String value) {
            addCriterion("shipper not like", value, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperIn(List<String> values) {
            addCriterion("shipper in", values, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperNotIn(List<String> values) {
            addCriterion("shipper not in", values, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperBetween(String value1, String value2) {
            addCriterion("shipper between", value1, value2, "shipper");
            return (Criteria) this;
        }

        public Criteria andShipperNotBetween(String value1, String value2) {
            addCriterion("shipper not between", value1, value2, "shipper");
            return (Criteria) this;
        }

        public Criteria andBlTitleIsNull() {
            addCriterion("bl_title is null");
            return (Criteria) this;
        }

        public Criteria andBlTitleIsNotNull() {
            addCriterion("bl_title is not null");
            return (Criteria) this;
        }

        public Criteria andBlTitleEqualTo(String value) {
            addCriterion("bl_title =", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleNotEqualTo(String value) {
            addCriterion("bl_title <>", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleGreaterThan(String value) {
            addCriterion("bl_title >", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleGreaterThanOrEqualTo(String value) {
            addCriterion("bl_title >=", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleLessThan(String value) {
            addCriterion("bl_title <", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleLessThanOrEqualTo(String value) {
            addCriterion("bl_title <=", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleLike(String value) {
            addCriterion("bl_title like", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleNotLike(String value) {
            addCriterion("bl_title not like", value, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleIn(List<String> values) {
            addCriterion("bl_title in", values, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleNotIn(List<String> values) {
            addCriterion("bl_title not in", values, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleBetween(String value1, String value2) {
            addCriterion("bl_title between", value1, value2, "blTitle");
            return (Criteria) this;
        }

        public Criteria andBlTitleNotBetween(String value1, String value2) {
            addCriterion("bl_title not between", value1, value2, "blTitle");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByIsNull() {
            addCriterion("original_notified_by is null");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByIsNotNull() {
            addCriterion("original_notified_by is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByEqualTo(String value) {
            addCriterion("original_notified_by =", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByNotEqualTo(String value) {
            addCriterion("original_notified_by <>", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByGreaterThan(String value) {
            addCriterion("original_notified_by >", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("original_notified_by >=", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByLessThan(String value) {
            addCriterion("original_notified_by <", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByLessThanOrEqualTo(String value) {
            addCriterion("original_notified_by <=", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByLike(String value) {
            addCriterion("original_notified_by like", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByNotLike(String value) {
            addCriterion("original_notified_by not like", value, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByIn(List<String> values) {
            addCriterion("original_notified_by in", values, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByNotIn(List<String> values) {
            addCriterion("original_notified_by not in", values, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByBetween(String value1, String value2) {
            addCriterion("original_notified_by between", value1, value2, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andOriginalNotifiedByNotBetween(String value1, String value2) {
            addCriterion("original_notified_by not between", value1, value2, "originalNotifiedBy");
            return (Criteria) this;
        }

        public Criteria andCreditLetterIsNull() {
            addCriterion("credit_letter is null");
            return (Criteria) this;
        }

        public Criteria andCreditLetterIsNotNull() {
            addCriterion("credit_letter is not null");
            return (Criteria) this;
        }

        public Criteria andCreditLetterEqualTo(String value) {
            addCriterion("credit_letter =", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterNotEqualTo(String value) {
            addCriterion("credit_letter <>", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterGreaterThan(String value) {
            addCriterion("credit_letter >", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterGreaterThanOrEqualTo(String value) {
            addCriterion("credit_letter >=", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterLessThan(String value) {
            addCriterion("credit_letter <", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterLessThanOrEqualTo(String value) {
            addCriterion("credit_letter <=", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterLike(String value) {
            addCriterion("credit_letter like", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterNotLike(String value) {
            addCriterion("credit_letter not like", value, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterIn(List<String> values) {
            addCriterion("credit_letter in", values, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterNotIn(List<String> values) {
            addCriterion("credit_letter not in", values, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterBetween(String value1, String value2) {
            addCriterion("credit_letter between", value1, value2, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andCreditLetterNotBetween(String value1, String value2) {
            addCriterion("credit_letter not between", value1, value2, "creditLetter");
            return (Criteria) this;
        }

        public Criteria andLoadingPortIsNull() {
            addCriterion("loading_port is null");
            return (Criteria) this;
        }

        public Criteria andLoadingPortIsNotNull() {
            addCriterion("loading_port is not null");
            return (Criteria) this;
        }

        public Criteria andLoadingPortEqualTo(String value) {
            addCriterion("loading_port =", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortNotEqualTo(String value) {
            addCriterion("loading_port <>", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortGreaterThan(String value) {
            addCriterion("loading_port >", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortGreaterThanOrEqualTo(String value) {
            addCriterion("loading_port >=", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortLessThan(String value) {
            addCriterion("loading_port <", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortLessThanOrEqualTo(String value) {
            addCriterion("loading_port <=", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortLike(String value) {
            addCriterion("loading_port like", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortNotLike(String value) {
            addCriterion("loading_port not like", value, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortIn(List<String> values) {
            addCriterion("loading_port in", values, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortNotIn(List<String> values) {
            addCriterion("loading_port not in", values, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortBetween(String value1, String value2) {
            addCriterion("loading_port between", value1, value2, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andLoadingPortNotBetween(String value1, String value2) {
            addCriterion("loading_port not between", value1, value2, "loadingPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortIsNull() {
            addCriterion("transhipment_port is null");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortIsNotNull() {
            addCriterion("transhipment_port is not null");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortEqualTo(String value) {
            addCriterion("transhipment_port =", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortNotEqualTo(String value) {
            addCriterion("transhipment_port <>", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortGreaterThan(String value) {
            addCriterion("transhipment_port >", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortGreaterThanOrEqualTo(String value) {
            addCriterion("transhipment_port >=", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortLessThan(String value) {
            addCriterion("transhipment_port <", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortLessThanOrEqualTo(String value) {
            addCriterion("transhipment_port <=", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortLike(String value) {
            addCriterion("transhipment_port like", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortNotLike(String value) {
            addCriterion("transhipment_port not like", value, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortIn(List<String> values) {
            addCriterion("transhipment_port in", values, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortNotIn(List<String> values) {
            addCriterion("transhipment_port not in", values, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortBetween(String value1, String value2) {
            addCriterion("transhipment_port between", value1, value2, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andTranshipmentPortNotBetween(String value1, String value2) {
            addCriterion("transhipment_port not between", value1, value2, "transhipmentPort");
            return (Criteria) this;
        }

        public Criteria andDischargePortIsNull() {
            addCriterion("discharge_port is null");
            return (Criteria) this;
        }

        public Criteria andDischargePortIsNotNull() {
            addCriterion("discharge_port is not null");
            return (Criteria) this;
        }

        public Criteria andDischargePortEqualTo(String value) {
            addCriterion("discharge_port =", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortNotEqualTo(String value) {
            addCriterion("discharge_port <>", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortGreaterThan(String value) {
            addCriterion("discharge_port >", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortGreaterThanOrEqualTo(String value) {
            addCriterion("discharge_port >=", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortLessThan(String value) {
            addCriterion("discharge_port <", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortLessThanOrEqualTo(String value) {
            addCriterion("discharge_port <=", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortLike(String value) {
            addCriterion("discharge_port like", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortNotLike(String value) {
            addCriterion("discharge_port not like", value, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortIn(List<String> values) {
            addCriterion("discharge_port in", values, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortNotIn(List<String> values) {
            addCriterion("discharge_port not in", values, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortBetween(String value1, String value2) {
            addCriterion("discharge_port between", value1, value2, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andDischargePortNotBetween(String value1, String value2) {
            addCriterion("discharge_port not between", value1, value2, "dischargePort");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeIsNull() {
            addCriterion("loading_time is null");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeIsNotNull() {
            addCriterion("loading_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeEqualTo(Date value) {
            addCriterion("loading_time =", value, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeNotEqualTo(Date value) {
            addCriterion("loading_time <>", value, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeGreaterThan(Date value) {
            addCriterion("loading_time >", value, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loading_time >=", value, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeLessThan(Date value) {
            addCriterion("loading_time <", value, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeLessThanOrEqualTo(Date value) {
            addCriterion("loading_time <=", value, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeIn(List<Date> values) {
            addCriterion("loading_time in", values, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeNotIn(List<Date> values) {
            addCriterion("loading_time not in", values, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeBetween(Date value1, Date value2) {
            addCriterion("loading_time between", value1, value2, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andLoadingTimeNotBetween(Date value1, Date value2) {
            addCriterion("loading_time not between", value1, value2, "loadingTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeIsNull() {
            addCriterion("effective_time is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeIsNotNull() {
            addCriterion("effective_time is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeEqualTo(Date value) {
            addCriterion("effective_time =", value, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeNotEqualTo(Date value) {
            addCriterion("effective_time <>", value, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeGreaterThan(Date value) {
            addCriterion("effective_time >", value, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("effective_time >=", value, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeLessThan(Date value) {
            addCriterion("effective_time <", value, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("effective_time <=", value, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeIn(List<Date> values) {
            addCriterion("effective_time in", values, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeNotIn(List<Date> values) {
            addCriterion("effective_time not in", values, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeBetween(Date value1, Date value2) {
            addCriterion("effective_time between", value1, value2, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andEffectiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("effective_time not between", value1, value2, "effectiveTime");
            return (Criteria) this;
        }

        public Criteria andIfBatchesIsNull() {
            addCriterion("if_batches is null");
            return (Criteria) this;
        }

        public Criteria andIfBatchesIsNotNull() {
            addCriterion("if_batches is not null");
            return (Criteria) this;
        }

        public Criteria andIfBatchesEqualTo(String value) {
            addCriterion("if_batches =", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesNotEqualTo(String value) {
            addCriterion("if_batches <>", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesGreaterThan(String value) {
            addCriterion("if_batches >", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesGreaterThanOrEqualTo(String value) {
            addCriterion("if_batches >=", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesLessThan(String value) {
            addCriterion("if_batches <", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesLessThanOrEqualTo(String value) {
            addCriterion("if_batches <=", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesLike(String value) {
            addCriterion("if_batches like", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesNotLike(String value) {
            addCriterion("if_batches not like", value, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesIn(List<String> values) {
            addCriterion("if_batches in", values, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesNotIn(List<String> values) {
            addCriterion("if_batches not in", values, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesBetween(String value1, String value2) {
            addCriterion("if_batches between", value1, value2, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfBatchesNotBetween(String value1, String value2) {
            addCriterion("if_batches not between", value1, value2, "ifBatches");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentIsNull() {
            addCriterion("if_transshipment is null");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentIsNotNull() {
            addCriterion("if_transshipment is not null");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentEqualTo(String value) {
            addCriterion("if_transshipment =", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentNotEqualTo(String value) {
            addCriterion("if_transshipment <>", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentGreaterThan(String value) {
            addCriterion("if_transshipment >", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentGreaterThanOrEqualTo(String value) {
            addCriterion("if_transshipment >=", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentLessThan(String value) {
            addCriterion("if_transshipment <", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentLessThanOrEqualTo(String value) {
            addCriterion("if_transshipment <=", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentLike(String value) {
            addCriterion("if_transshipment like", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentNotLike(String value) {
            addCriterion("if_transshipment not like", value, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentIn(List<String> values) {
            addCriterion("if_transshipment in", values, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentNotIn(List<String> values) {
            addCriterion("if_transshipment not in", values, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentBetween(String value1, String value2) {
            addCriterion("if_transshipment between", value1, value2, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andIfTransshipmentNotBetween(String value1, String value2) {
            addCriterion("if_transshipment not between", value1, value2, "ifTransshipment");
            return (Criteria) this;
        }

        public Criteria andCopiesNoIsNull() {
            addCriterion("copies_no is null");
            return (Criteria) this;
        }

        public Criteria andCopiesNoIsNotNull() {
            addCriterion("copies_no is not null");
            return (Criteria) this;
        }

        public Criteria andCopiesNoEqualTo(String value) {
            addCriterion("copies_no =", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoNotEqualTo(String value) {
            addCriterion("copies_no <>", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoGreaterThan(String value) {
            addCriterion("copies_no >", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoGreaterThanOrEqualTo(String value) {
            addCriterion("copies_no >=", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoLessThan(String value) {
            addCriterion("copies_no <", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoLessThanOrEqualTo(String value) {
            addCriterion("copies_no <=", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoLike(String value) {
            addCriterion("copies_no like", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoNotLike(String value) {
            addCriterion("copies_no not like", value, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoIn(List<String> values) {
            addCriterion("copies_no in", values, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoNotIn(List<String> values) {
            addCriterion("copies_no not in", values, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoBetween(String value1, String value2) {
            addCriterion("copies_no between", value1, value2, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andCopiesNoNotBetween(String value1, String value2) {
            addCriterion("copies_no not between", value1, value2, "copiesNo");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionIsNull() {
            addCriterion("brief_description is null");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionIsNotNull() {
            addCriterion("brief_description is not null");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionEqualTo(String value) {
            addCriterion("brief_description =", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionNotEqualTo(String value) {
            addCriterion("brief_description <>", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionGreaterThan(String value) {
            addCriterion("brief_description >", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("brief_description >=", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionLessThan(String value) {
            addCriterion("brief_description <", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionLessThanOrEqualTo(String value) {
            addCriterion("brief_description <=", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionLike(String value) {
            addCriterion("brief_description like", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionNotLike(String value) {
            addCriterion("brief_description not like", value, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionIn(List<String> values) {
            addCriterion("brief_description in", values, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionNotIn(List<String> values) {
            addCriterion("brief_description not in", values, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionBetween(String value1, String value2) {
            addCriterion("brief_description between", value1, value2, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andBriefDescriptionNotBetween(String value1, String value2) {
            addCriterion("brief_description not between", value1, value2, "briefDescription");
            return (Criteria) this;
        }

        public Criteria andRequirementsIsNull() {
            addCriterion("requirements is null");
            return (Criteria) this;
        }

        public Criteria andRequirementsIsNotNull() {
            addCriterion("requirements is not null");
            return (Criteria) this;
        }

        public Criteria andRequirementsEqualTo(String value) {
            addCriterion("requirements =", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsNotEqualTo(String value) {
            addCriterion("requirements <>", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsGreaterThan(String value) {
            addCriterion("requirements >", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsGreaterThanOrEqualTo(String value) {
            addCriterion("requirements >=", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsLessThan(String value) {
            addCriterion("requirements <", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsLessThanOrEqualTo(String value) {
            addCriterion("requirements <=", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsLike(String value) {
            addCriterion("requirements like", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsNotLike(String value) {
            addCriterion("requirements not like", value, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsIn(List<String> values) {
            addCriterion("requirements in", values, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsNotIn(List<String> values) {
            addCriterion("requirements not in", values, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsBetween(String value1, String value2) {
            addCriterion("requirements between", value1, value2, "requirements");
            return (Criteria) this;
        }

        public Criteria andRequirementsNotBetween(String value1, String value2) {
            addCriterion("requirements not between", value1, value2, "requirements");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionIsNull() {
            addCriterion("freight_description is null");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionIsNotNull() {
            addCriterion("freight_description is not null");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionEqualTo(String value) {
            addCriterion("freight_description =", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionNotEqualTo(String value) {
            addCriterion("freight_description <>", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionGreaterThan(String value) {
            addCriterion("freight_description >", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("freight_description >=", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionLessThan(String value) {
            addCriterion("freight_description <", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionLessThanOrEqualTo(String value) {
            addCriterion("freight_description <=", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionLike(String value) {
            addCriterion("freight_description like", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionNotLike(String value) {
            addCriterion("freight_description not like", value, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionIn(List<String> values) {
            addCriterion("freight_description in", values, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionNotIn(List<String> values) {
            addCriterion("freight_description not in", values, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionBetween(String value1, String value2) {
            addCriterion("freight_description between", value1, value2, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andFreightDescriptionNotBetween(String value1, String value2) {
            addCriterion("freight_description not between", value1, value2, "freightDescription");
            return (Criteria) this;
        }

        public Criteria andReviewerIsNull() {
            addCriterion("reviewer is null");
            return (Criteria) this;
        }

        public Criteria andReviewerIsNotNull() {
            addCriterion("reviewer is not null");
            return (Criteria) this;
        }

        public Criteria andReviewerEqualTo(String value) {
            addCriterion("reviewer =", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotEqualTo(String value) {
            addCriterion("reviewer <>", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerGreaterThan(String value) {
            addCriterion("reviewer >", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerGreaterThanOrEqualTo(String value) {
            addCriterion("reviewer >=", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerLessThan(String value) {
            addCriterion("reviewer <", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerLessThanOrEqualTo(String value) {
            addCriterion("reviewer <=", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerLike(String value) {
            addCriterion("reviewer like", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotLike(String value) {
            addCriterion("reviewer not like", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerIn(List<String> values) {
            addCriterion("reviewer in", values, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotIn(List<String> values) {
            addCriterion("reviewer not in", values, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerBetween(String value1, String value2) {
            addCriterion("reviewer between", value1, value2, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotBetween(String value1, String value2) {
            addCriterion("reviewer not between", value1, value2, "reviewer");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDeptIsNull() {
            addCriterion("create_dept is null");
            return (Criteria) this;
        }

        public Criteria andCreateDeptIsNotNull() {
            addCriterion("create_dept is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDeptEqualTo(String value) {
            addCriterion("create_dept =", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptNotEqualTo(String value) {
            addCriterion("create_dept <>", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptGreaterThan(String value) {
            addCriterion("create_dept >", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptGreaterThanOrEqualTo(String value) {
            addCriterion("create_dept >=", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptLessThan(String value) {
            addCriterion("create_dept <", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptLessThanOrEqualTo(String value) {
            addCriterion("create_dept <=", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptLike(String value) {
            addCriterion("create_dept like", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptNotLike(String value) {
            addCriterion("create_dept not like", value, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptIn(List<String> values) {
            addCriterion("create_dept in", values, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptNotIn(List<String> values) {
            addCriterion("create_dept not in", values, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptBetween(String value1, String value2) {
            addCriterion("create_dept between", value1, value2, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateDeptNotBetween(String value1, String value2) {
            addCriterion("create_dept not between", value1, value2, "createDept");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table co_shipping
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable{

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    public static class Criterion implements Serializable{
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}