package cn.itcast.dao.cargo;

import cn.itcast.domain.cargo.Shipping;
import cn.itcast.domain.cargo.ShippingExample;
import java.util.List;

public interface ShippingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String shippingOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    List<Shipping> selectByExample(ShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    Shipping selectByPrimaryKey(String shippingOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Shipping record);

}